"use client";

import { Container } from "@mui/material";
import { Inter } from "next/font/google";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Layout({ children }: { children: React.ReactElement }) {
  return (
    <html>
      <head></head>
      <body className={inter.className}>
        <Container maxWidth='lg'>{children}</Container>
      </body>
    </html>
  );
}

export default Layout;
