"use client";

import { getSlug } from "@/libs/mdx";
import { Metadata } from "next";
import Link from "next/link";
import React, { use } from "react";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};



export default async function Page(props: any) {
  const { pathList } = await getData()
  return <div>
    <ol>
      {pathList.map((path: string, i: number) => <Link key={i} href={'/blog/' + path}>{path}</Link>)}
    </ol>
  </div>;
}

async function getData() {
  const slugs = await fetch('http://localhost:3000/api/blog/name');
  return await slugs.json();
}
