import Layout from "@/layouts/Layout";
import { Metadata } from "next";
import { getAllArticles } from "../src/libs/mdx";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Home({ posts }: any) {
  return <Layout>{posts.length}</Layout>;
}

export async function getStaticProps() {
  const articles = await getAllArticles();

  articles
    .map((article: any) => article.data)
    .sort(
      (
        a: { data: { publishedAt: number } },
        b: { data: { publishedAt: number } }
      ) => {
        if (a.data.publishedAt > b.data.publishedAt) return 1;
        if (a.data.publishedAt < b.data.publishedAt) return -1;

        return 0;
      }
    );

  return {
    props: {
      posts: articles.reverse(),
    },
  };
}
